In [1]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

Instructions for updating:
non-resource variables are not supported in the long term


In [4]:
a = tf.constant([9, 8, 7], name = 'a')
b = tf.constant([1, 2, 3], name = 'b')

In [5]:
soma1 = a + b

In [7]:
with tf.Session() as sess:
    print(sess.run(soma))

[10 10 10]


In [14]:
c = tf.constant([[1, 2, 3], [4, 5, 6]], name = 'c')
d = tf.constant([[1, 2, 3], [4, 5, 6]], name = 'd')

In [15]:
#mostrar o tamanho do array
c.shape 

TensorShape([Dimension(2), Dimension(3)])

In [16]:
soma2 = tf.add(c, d)

In [20]:
with tf.Session() as sess:
    print(sess.run(c))
    print('\n')
    print(sess.run(d))
    print('\n')
    print(sess.run(soma2))

[[1 2 3]
 [4 5 6]]


[[1 2 3]
 [4 5 6]]


[[ 2  4  6]
 [ 8 10 12]]


In [21]:
e = tf.constant([[1, 2, 3], [4, 5, 6]], name = 'e')
f = tf.constant([[1], [2]], name = 'f')

In [23]:
soma3 = tf.add(e, f)

In [24]:
with tf.Session() as sess:
    print(sess.run(e))
    print('\n')
    print(sess.run(f))
    print('\n')
    print(sess.run(soma3))

[[1 2 3]
 [4 5 6]]


[[1]
 [2]]


[[2 3 4]
 [6 7 8]]
