In [1]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

Instructions for updating:
non-resource variables are not supported in the long term


In [12]:
p1 = tf.placeholder('float', None) 
# Placeholder é simplesmente uma variável à qual atribuiremos dados posteriormente.

In [13]:
operacao1 = p1 + 2

In [14]:
with tf.Session() as sess:
    #sess.run(operacao)
    resultado = sess.run(operacao1, feed_dict = {p1: [1, 2, 3]})
    print(resultado)

[3. 4. 5.]


In [15]:
p2 = tf.placeholder('float', [None, 5]) 

In [17]:
operacao2 = p2* 5

In [18]:
with tf.Session() as sess:
    #sess.run(operacao)
    dados = [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]
    resultado = sess.run(operacao2, feed_dict={p2: dados})
    print(resultado)

[[ 5. 10. 15. 20. 25.]
 [30. 35. 40. 45. 50.]]
