In [1]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

Instructions for updating:
non-resource variables are not supported in the long term


In [2]:
a = tf.constant([[1, 2], [3, 4]], name = 'a')
b = tf.constant([[-1, 3], [4, 2]], name = 'b')

In [3]:
# Multiplicação Para matrizes
multiplicacao1 = tf.matmul(a, b) 

In [4]:
with tf.Session() as sess:
    print(sess.run(a))
    print('\n')
    print(sess.run(b))
    print('\n')
    print(sess.run(multiplicacao1))

[[1 2]
 [3 4]]


[[-1  3]
 [ 4  2]]


[[ 7  7]
 [13 17]]


In [12]:
# Multiplicação Para matrizes
multiplicacao2 = tf.matmul(b, a) 

In [13]:
with tf.Session() as sess:
    print(sess.run(b))
    print('\n')
    print(sess.run(a))
    print('\n')
    print(sess.run(multiplicacao2))

[[-1  3]
 [ 4  2]]


[[1 2]
 [3 4]]


[[ 8 10]
 [10 16]]


In [14]:
c = tf.constant([[2, 3], [0, 1], [-1, 4]], name = 'c')
d = tf.constant([[1, 2, 3], [-2, 0, 4]], name = 'd')
multiplicacao3 = tf.matmul(c, d) 

In [15]:
with tf.Session() as sess:
    print(sess.run(c))
    print('\n')
    print(sess.run(d))
    print('\n')
    print(sess.run(multiplicacao3))

[[ 2  3]
 [ 0  1]
 [-1  4]]


[[ 1  2  3]
 [-2  0  4]]


[[-4  4 18]
 [-2  0  4]
 [-9 -2 13]]
